#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# Get the path to the project from which this script was called
#------------------------------------------------------------------------------#

src_dir="${0%/*}/../.."

#------------------------------------------------------------------------------#
# Call CMake command
#------------------------------------------------------------------------------#

cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DENABLE_INTEGRATED_TESTS=OFF \
  -DENABLE_UNIT_TESTS=OFF \
  -DCMAKE_C_COMPILER=icc \
  -DCMAKE_CXX_COMPILER=icpc \
  -DCMAKE_C_FLAGS="-O3 -rdynamic -inline-forceinline  \
  -qoverride-limits -no-ansi-alias -xCORE-AVX2" \
  -DCMAKE_CXX_FLAGS="-O3 -rdynamic -inline-forceinline \
  -qoverride-limits -no-ansi-alias -xCORE-AVX2" \
  -DUSE_V4_AVX2=ON \
  -DUSE_V8_AVX2=ON \
  $src_dir
